import { useEffect, useState } from "react";
import { ArrowLeft, Languages, LogOut, RefreshCw } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { useLanguage } from "@/hooks/useLanguage";
import { isAdminUser, isSupabaseConfigured, supabase } from "@/lib/supabase";

type Application = { id: string; applicant_name: string; email: string; phone: string; cover_message: string; status: "new" | "reviewing" | "shortlisted" | "rejected" | "hired"; created_at: string; career_post_id: string | null };
export default function AdminApplications() { const navigate = useNavigate(); const { isBn, toggleLanguage } = useLanguage(); const [items, setItems] = useState<Application[]>([]); const [loading, setLoading] = useState(true);
  async function load() { if (!supabase) return; setLoading(true); const { data: { user } } = await supabase.auth.getUser(); if (!user || !isAdminUser(user)) { navigate("/admin/login", { replace: true }); return; } const { data, error } = await supabase.from("career_applications").select("*").order("created_at", { ascending: false }); if (error) toast.error(error.message); setItems((data as Application[] | null) ?? []); setLoading(false); }
  useEffect(() => { void load(); }, []);
  async function updateStatus(id: string, status: Application["status"]) { if (!supabase) return; const { error } = await supabase.from("career_applications").update({ status }).eq("id", id); if (error) { toast.error(error.message); return; } setItems((current) => current.map((item) => item.id === id ? { ...item, status } : item)); toast.success(isBn ? "আবেদনের অবস্থা আপডেট হয়েছে" : "Application status updated"); }
  if (!isSupabaseConfigured) return <main className="auth-page"><div className="auth-card"><h1>{isBn ? "কনফিগারেশন প্রয়োজন" : "Configuration required"}</h1></div></main>;
  return <main className="admin-page"><header className="admin-header"><div><span className="section-label">{isBn ? "অ্যাডমিন / ক্যারিয়ার" : "ADMIN / CAREERS"}</span><h1>{isBn ? "আবেদনসমূহ" : "Applications"}</h1></div><div className="admin-actions"><button className="language-toggle" onClick={toggleLanguage}><Languages size={14} /> {isBn ? "EN" : "বাংলা"}</button><button className="button button--small button--sand" onClick={() => void load()}><RefreshCw size={15} /> {isBn ? "রিফ্রেশ" : "Refresh"}</button><button className="button button--small button--brown" onClick={() => void (supabase?.auth.signOut().then(() => navigate("/")))}><LogOut size={15} /> {isBn ? "বের হন" : "Sign out"}</button></div></header><div className="admin-toolbar"><Link className="text-link" to="/admin"><ArrowLeft size={16} /> {isBn ? "অ্যাডমিন হাবে ফিরুন" : "Back to admin hub"}</Link><span>{items.length} {isBn ? "টি আবেদন" : items.length === 1 ? "application" : "applications"}</span></div>{loading ? <div className="admin-empty">{isBn ? "আবেদন লোড হচ্ছে…" : "Loading applications…"}</div> : items.length === 0 ? <div className="admin-empty"><h2>{isBn ? "এখনও কোনো আবেদন নেই" : "No applications yet"}</h2><p>{isBn ? "ক্যারিয়ার পেজ থেকে আবেদন এলে এখানে দেখা যাবে।" : "Applications from the careers page will appear here."}</p></div> : <div className="inquiry-list">{items.map((item) => <article className="inquiry-card" key={item.id}><div className="inquiry-card-top"><div><span className="inquiry-date">{new Date(item.created_at).toLocaleString()}</span><h2>{item.applicant_name}</h2></div><select value={item.status} onChange={(event) => void updateStatus(item.id, event.target.value as Application["status"])}><option value="new">{isBn ? "নতুন" : "New"}</option><option value="reviewing">{isBn ? "পর্যালোচনাধীন" : "Reviewing"}</option><option value="shortlisted">{isBn ? "শর্টলিস্ট" : "Shortlisted"}</option><option value="rejected">{isBn ? "বাতিল" : "Rejected"}</option><option value="hired">{isBn ? "নিয়োগপ্রাপ্ত" : "Hired"}</option></select></div><div className="inquiry-contact"><a href={`mailto:${item.email}`}>{item.email}</a><a href={`tel:${item.phone}`}>{item.phone}</a></div><p>{item.cover_message}</p></article>)}</div>}</main>; }
