import { ArrowLeft, ArrowUpRight, Languages } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { useEffect, useState } from "react";
import { useLanguage } from "@/hooks/useLanguage";
import { BlogPost, supabase } from "@/lib/supabase";

export default function Blog() {
  const { isBn, toggleLanguage } = useLanguage();
  const [searchParams] = useSearchParams();
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { if (!supabase) { setLoading(false); return; } supabase.from("blog_posts").select("*").eq("is_published", true).order("published_at", { ascending: false }).then(({ data }) => { setPosts((data as BlogPost[] | null) ?? []); setLoading(false); }); }, []);
  const selected = searchParams.get("post") ? posts.find((post) => post.slug === searchParams.get("post")) : null;
  return <main className="blog-page"><header className="careers-header"><Link className="auth-back" to="/"><ArrowLeft size={16} /> {isBn ? "হোমে ফিরুন" : "Back to website"}</Link><button className="language-toggle" type="button" onClick={toggleLanguage}><Languages size={14} /> {isBn ? "EN" : "বাংলা"}</button></header><section className="blog-hero"><span className="section-label">{isBn ? "ব্লগ / কারিগরি নোট" : "BLOG / TECHNICAL NOTES"}</span><h1>{isBn ? "ভালো সিদ্ধান্তের জন্য কারিগরি জ্ঞান।" : "Technical knowledge for better decisions."}</h1><p>{isBn ? "মাটি, কাঠামো, জরিপ ও নির্মাণ পরামর্শ নিয়ে সিভিল সলিউশনের নোট।" : "Civil Solution notes on soil, structures, surveying, and practical construction decisions."}</p></section><section className="blog-list">{loading ? <div className="admin-empty">{isBn ? "ব্লগ লোড হচ্ছে…" : "Loading articles…"}</div> : posts.length === 0 ? <div className="admin-empty"><h2>{isBn ? "শীঘ্রই নতুন লেখা আসছে" : "Articles are coming soon"}</h2><p>{isBn ? "নতুন কারিগরি লেখা প্রকাশ হলে এখানে দেখা যাবে।" : "New technical articles will appear here when published."}</p></div> : selected ? <article className="blog-article"><Link className="text-link" to="/blog"><ArrowLeft size={16} /> {isBn ? "সব লেখা দেখুন" : "All articles"}</Link><span className="blog-category">{selected.category}</span><h2>{isBn ? selected.title_bn : selected.title_en}</h2><p className="blog-date">{selected.published_at ? new Date(selected.published_at).toLocaleDateString() : ""}</p><div className="blog-content">{(isBn ? selected.content_bn : selected.content_en).split(/\n\n+/).map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div></article> : <div className="blog-grid">{posts.map((post) => <Link className="blog-card" to={`/blog?post=${post.slug}`} key={post.id}>{post.cover_image && <img src={post.cover_image} alt="" /> }<span className="blog-category">{post.category}</span><h2>{isBn ? post.title_bn : post.title_en}</h2><p>{isBn ? post.excerpt_bn : post.excerpt_en}</p><span className="text-link">{isBn ? "পড়ুন" : "Read article"} <ArrowUpRight size={15} /></span></Link>)}</div>}</section></main>;
}
