export type AreaOption = { en: string; bn: string };

export const OTHER_AREA_VALUE = "Other area / district";

export const bangladeshAreas: AreaOption[] = [
  { en: "Dhaka", bn: "ঢাকা" },
  { en: "Chattogram", bn: "চট্টগ্রাম" },
  { en: "Cox's Bazar", bn: "কক্সবাজার" },
  { en: "Cumilla", bn: "কুমিল্লা" },
  { en: "Feni", bn: "ফেনী" },
  { en: "Noakhali", bn: "নোয়াখালী" },
  { en: "Lakshmipur", bn: "লক্ষ্মীপুর" },
  { en: "Chandpur", bn: "চাঁদপুর" },
  { en: "Brahmanbaria", bn: "ব্রাহ্মণবাড়িয়া" },
  { en: "Rajshahi", bn: "রাজশাহী" },
  { en: "Rangpur", bn: "রংপুর" },
  { en: "Khulna", bn: "খুলনা" },
  { en: "Barishal", bn: "বরিশাল" },
  { en: "Sylhet", bn: "সিলেট" },
  { en: "Mymensingh", bn: "ময়মনসিংহ" },
  { en: "Gazipur", bn: "গাজীপুর" },
  { en: "Narayanganj", bn: "নারায়ণগঞ্জ" },
  { en: "Narsingdi", bn: "নরসিংদী" },
  { en: "Tangail", bn: "টাঙ্গাইল" },
  { en: "Manikganj", bn: "মানিকগঞ্জ" },
  { en: "Munshiganj", bn: "মুন্সিগঞ্জ" },
  { en: "Kishoreganj", bn: "কিশোরগঞ্জ" },
  { en: "Faridpur", bn: "ফরিদপুর" },
  { en: "Gopalganj", bn: "গোপালগঞ্জ" },
  { en: "Madaripur", bn: "মাদারীপুর" },
  { en: "Shariatpur", bn: "শরীয়তপুর" },
  { en: "Rajbari", bn: "রাজবাড়ী" },
  { en: "Bagerhat", bn: "বাগেরহাট" },
  { en: "Chuadanga", bn: "চুয়াডাঙ্গা" },
  { en: "Jashore", bn: "যশোর" },
  { en: "Jhenaidah", bn: "ঝিনাইদহ" },
  { en: "Kushtia", bn: "কুষ্টিয়া" },
  { en: "Magura", bn: "মাগুরা" },
  { en: "Meherpur", bn: "মেহেরপুর" },
  { en: "Narail", bn: "নড়াইল" },
  { en: "Satkhira", bn: "সাতক্ষীরা" },
  { en: "Bogra", bn: "বগুড়া" },
  { en: "Joypurhat", bn: "জয়পুরহাট" },
  { en: "Naogaon", bn: "নওগাঁ" },
  { en: "Natore", bn: "নাটোর" },
  { en: "Chapainawabganj", bn: "চাঁপাইনবাবগঞ্জ" },
  { en: "Pabna", bn: "পাবনা" },
  { en: "Sirajganj", bn: "সিরাজগঞ্জ" },
  { en: "Dinajpur", bn: "দিনাজপুর" },
  { en: "Gaibandha", bn: "গাইবান্ধা" },
  { en: "Kurigram", bn: "কুড়িগ্রাম" },
  { en: "Lalmonirhat", bn: "লালমনিরহাট" },
  { en: "Nilphamari", bn: "নীলফামারী" },
  { en: "Panchagarh", bn: "পঞ্চগড়" },
  { en: "Thakurgaon", bn: "ঠাকুরগাঁও" },
  { en: "Barguna", bn: "বরগুনা" },
  { en: "Bhola", bn: "ভোলা" },
  { en: "Jhalokathi", bn: "ঝালকাঠি" },
  { en: "Patuakhali", bn: "পটুয়াখালী" },
  { en: "Pirojpur", bn: "পিরোজপুর" },
  { en: "Habiganj", bn: "হবিগঞ্জ" },
  { en: "Moulvibazar", bn: "মৌলভীবাজার" },
  { en: "Sunamganj", bn: "সুনামগঞ্জ" },
  { en: "Jamalpur", bn: "জামালপুর" },
  { en: "Netrokona", bn: "নেত্রকোনা" },
  { en: "Sherpur", bn: "শেরপুর" },
  { en: "Other area / district", bn: "অন্যান্য এলাকা / জেলা" },
];
